###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    mysql:
      image: mysql:5.7
      container_name: poundelectionsymfony-mysql
      working_dir: /application
      hostname: mysql
      command: --sql_mode="" #used to not enable strict mode in sql
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=Pound3lection2018
        - MYSQL_DATABASE=poundElections
        - MYSQL_USER=electionAdmin
        - MYSQL_PASSWORD=Pound3lection2018
      ports:
        - "8082:3306"

    webserver:
      image: nginx:alpine
      container_name: poundelectionsymfony-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8080:80"
      links:
       - mysql

    php-fpm:
      build: phpdocker/php-fpm
      container_name: poundelectionsymfony-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini
      links:
        - mysql
